// Objective-C API for talking to github.com/TheRealBeetle/android-client-lib Go package.
//   gobind -lang=objc github.com/TheRealBeetle/android-client-lib
//
// File is generated by gobind. Do not edit.

#ifndef __Androidlib_H__
#define __Androidlib_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


@class AndroidlibAndroidSlab;
@class AndroidlibBeetlePrice;
@class AndroidlibLibAddress;
@class AndroidlibLibBalance;
@class AndroidlibLibClientTransationLoads;
@class AndroidlibLibClientTranstionItem;
@protocol AndroidlibShareDb;
@class AndroidlibShareDb;
@protocol AndroidlibVpnDelegate;
@class AndroidlibVpnDelegate;

@protocol AndroidlibShareDb <NSObject>
- (void)close;
- (NSString* _Nonnull)get:(NSString* _Nullable)key;
- (NSString* _Nonnull)list:(NSString* _Nullable)start end:(NSString* _Nullable)end;
- (NSString* _Nonnull)listAll;
- (long)put:(NSString* _Nullable)key value:(NSString* _Nullable)value;
@end

@protocol AndroidlibVpnDelegate <NSObject>
- (BOOL)bypass:(int32_t)fd;
- (void)vpnClosed;
- (BOOL)write:(NSData* _Nullable)p0 n:(long* _Nullable)n error:(NSError* _Nullable* _Nullable)error;
@end

@interface AndroidlibAndroidSlab : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) id<AndroidlibVpnDelegate> _Nullable delegate;
@property (nonatomic) id<AndroidlibShareDb> _Nullable shareDb;
// skipped field AndroidSlab.Cfg with unsupported type: *github.com/TheRealBeetle/beetle-client-lib/config.BtlClientConf

// skipped field AndroidSlab.Wallet with unsupported type: github.com/TheRealBeetle/beetle-protocol/remotewallet.RemoteWalletIntf

// skipped field AndroidSlab.T2s with unsupported type: *github.com/TheRealBeetle/android-client-lib/tun2Pipe.Tun2Pipe

@end

@interface AndroidlibBeetlePrice : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
// skipped field BeetlePrice.Price with unsupported type: *github.com/TheRealBeetle/beetle-protocol/miners.BeetlePrice

// skipped field BeetlePrice.Discount with unsupported type: *github.com/TheRealBeetle/beetle-protocol/miners.DiscountPrice

@end

@interface AndroidlibLibAddress : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull ethAddr;
@property (nonatomic) NSString* _Nonnull trxAddr;
@property (nonatomic) NSString* _Nonnull btlcAddr;
@property (nonatomic) NSString* _Nonnull usdtAddr;
@end

@interface AndroidlibLibBalance : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
// skipped field LibBalance.BeetleBalance with unsupported type: github.com/TheRealBeetle/beetle-client-lib/config.BeetleBalance

@end

@interface AndroidlibLibClientTransationLoads : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
// skipped field LibClientTransationLoads.Items with unsupported type: []*github.com/TheRealBeetle/android-client-lib.LibClientTranstionItem

@property (nonatomic) int64_t total;
@end

@interface AndroidlibLibClientTranstionItem : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
// skipped field LibClientTranstionItem.ClientTranstionItem with unsupported type: github.com/TheRealBeetle/beetle-client-lib/db.ClientTranstionItem

@property (nonatomic) NSString* _Nonnull txStr;
- (NSString* _Nonnull)string;
@end

FOUNDATION_EXPORT NSString* _Nonnull const AndroidlibDatabaseDir;

@interface Androidlib : NSObject
+ (AndroidlibAndroidSlab* _Nullable) beetleInstant;
+ (void) setBeetleInstant:(AndroidlibAndroidSlab* _Nullable)v;

@end

FOUNDATION_EXPORT BOOL AndroidlibCreateWallet(NSString* _Nullable auth, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT long AndroidlibGetCurStationId(void);

FOUNDATION_EXPORT NSString* _Nonnull AndroidlibGetCurStationName(void);

FOUNDATION_EXPORT NSString* _Nonnull AndroidlibGetDownLink(void);

FOUNDATION_EXPORT NSString* _Nonnull AndroidlibGetLicenseExpireDate(void);

FOUNDATION_EXPORT NSString* _Nonnull AndroidlibGetStationList(NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT long AndroidlibGetStreamPort(void);

FOUNDATION_EXPORT NSString* _Nonnull AndroidlibGetUpLink(void);

FOUNDATION_EXPORT BOOL AndroidlibGetVpnMode(void);

FOUNDATION_EXPORT BOOL AndroidlibInitBeetle(NSString* _Nullable ips, NSString* _Nullable basDir, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT BOOL AndroidlibInputPacket(NSData* _Nullable data, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT BOOL AndroidlibIsBeetleId(NSString* _Nullable id_);

FOUNDATION_EXPORT BOOL AndroidlibIsCommunicateWalletOpened(void);

FOUNDATION_EXPORT BOOL AndroidlibIsTokenWalletOpened(void);

FOUNDATION_EXPORT BOOL AndroidlibIsWalletCreate(void);

FOUNDATION_EXPORT NSString* _Nonnull AndroidlibLicenseBuy(NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT NSString* _Nonnull AndroidlibLicenseGetPrice(void);

FOUNDATION_EXPORT NSString* _Nonnull AndroidlibLicenseGetUserPrice(void);

FOUNDATION_EXPORT BOOL AndroidlibLicenseIsApplied(void);

FOUNDATION_EXPORT NSString* _Nonnull AndroidlibLicenseRenew(NSString* _Nullable tx, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT NSString* _Nonnull AndroidlibLicenseUserPrice(NSString* _Nullable licenseTime, long typ, NSString* _Nullable receiver, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT NSString* _Nonnull AndroidlibLicenseUserPriceThirdWallet(NSString* _Nullable licenseTime, long typ, NSString* _Nullable receiver, NSString* _Nullable payer, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT void AndroidlibLoadIps(NSString* _Nullable bypassIPs);

FOUNDATION_EXPORT NSString* _Nonnull AndroidlibLoadLicenseTransactions(long pageStart, long pageSize, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT NSString* _Nonnull AndroidlibMarketPriceGet(NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT BOOL AndroidlibOpenCommunicateWallet(NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT BOOL AndroidlibOpenTokenWallet(NSString* _Nullable auth, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT BOOL AndroidlibOpenWallet(NSString* _Nullable auth, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT BOOL AndroidlibRefreshBalance(NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT BOOL AndroidlibRefreshLicense(NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT BOOL AndroidlibRefreshStations(NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT NSString* _Nonnull AndroidlibRenewAllLicense(NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT BOOL AndroidlibSaveTransation(NSString* _Nullable tx, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT void AndroidlibSetCurStation(int64_t id_);

FOUNDATION_EXPORT void AndroidlibSetVpnMode(BOOL mode);

FOUNDATION_EXPORT BOOL AndroidlibStartVpn(NSString* _Nullable ipaddr, int64_t stationId, id<AndroidlibVpnDelegate> _Nullable vd, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT void AndroidlibStopVpn(void);

FOUNDATION_EXPORT NSString* _Nonnull AndroidlibTokenAddress(void);

FOUNDATION_EXPORT NSString* _Nonnull AndroidlibTokenBalances(void);

FOUNDATION_EXPORT BOOL AndroidlibTransactionInsert(NSString* _Nullable tx, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT BOOL AndroidlibUserReg(NSString* _Nullable email, NSString* _Nullable telegram, NSString* _Nullable passwd, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT BOOL AndroidlibVpnIsStarted(void);

@class AndroidlibShareDb;

@class AndroidlibVpnDelegate;

@interface AndroidlibShareDb : NSObject <goSeqRefInterface, AndroidlibShareDb> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (void)close;
- (NSString* _Nonnull)get:(NSString* _Nullable)key;
- (NSString* _Nonnull)list:(NSString* _Nullable)start end:(NSString* _Nullable)end;
- (NSString* _Nonnull)listAll;
- (long)put:(NSString* _Nullable)key value:(NSString* _Nullable)value;
@end

@interface AndroidlibVpnDelegate : NSObject <goSeqRefInterface, AndroidlibVpnDelegate> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (BOOL)bypass:(int32_t)fd;
- (void)vpnClosed;
- (BOOL)write:(NSData* _Nullable)p0 n:(long* _Nullable)n error:(NSError* _Nullable* _Nullable)error;
@end

#endif
