
// Objective-C API for talking to the following Go packages
//
//	github.com/TheRealBeetle/android-client-lib
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Macdss_FRAMEWORK_H__
#define __Macdss_FRAMEWORK_H__

#include "Androidlib.objc.h"
#include "Universe.objc.h"

#endif
