// Objective-C API for talking to github.com/TheRealBeetle/drawin-client-lib Go package.
//   gobind -lang=objc github.com/TheRealBeetle/drawin-client-lib
//
// File is generated by gobind. Do not edit.

#ifndef __DrawinBeetleLib_H__
#define __DrawinBeetleLib_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


@class DrawinBeetleLibBeetlePrice;
@class DrawinBeetleLibDrawinSlab;
@class DrawinBeetleLibLibAddress;
@class DrawinBeetleLibLibBalance;
@class DrawinBeetleLibLibClientTransationLoads;
@class DrawinBeetleLibLibClientTranstionItem;
@protocol DrawinBeetleLibShareDb;
@class DrawinBeetleLibShareDb;
@protocol DrawinBeetleLibVpnDelegate;
@class DrawinBeetleLibVpnDelegate;

@protocol DrawinBeetleLibShareDb <NSObject>
- (void)close;
- (NSString* _Nonnull)get:(NSString* _Nullable)key;
- (NSString* _Nonnull)list:(NSString* _Nullable)start end:(NSString* _Nullable)end;
- (NSString* _Nonnull)listAll;
- (long)put:(NSString* _Nullable)key value:(NSString* _Nullable)value;
@end

@protocol DrawinBeetleLibVpnDelegate <NSObject>
- (BOOL)bypass:(int32_t)fd;
- (void)vpnClosed;
- (BOOL)write:(NSData* _Nullable)p0 n:(long* _Nullable)n error:(NSError* _Nullable* _Nullable)error;
@end

@interface DrawinBeetleLibBeetlePrice : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
// skipped field BeetlePrice.Price with unsupported type: *github.com/TheRealBeetle/beetle-protocol/miners.BeetlePrice

// skipped field BeetlePrice.Discount with unsupported type: *github.com/TheRealBeetle/beetle-protocol/miners.DiscountPrice

@end

@interface DrawinBeetleLibDrawinSlab : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) id<DrawinBeetleLibVpnDelegate> _Nullable delegate;
@property (nonatomic) id<DrawinBeetleLibShareDb> _Nullable shareDb;
// skipped field DrawinSlab.Cfg with unsupported type: *github.com/TheRealBeetle/beetle-client-lib/config.BtlClientConf

// skipped field DrawinSlab.Wallet with unsupported type: github.com/TheRealBeetle/beetle-protocol/remotewallet.RemoteWalletIntf

// skipped field DrawinSlab.T2g with unsupported type: *github.com/TheRealBeetle/drawin-client-lib/gvisor.NetStack

- (void)close;
@end

@interface DrawinBeetleLibLibAddress : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull ethAddr;
@property (nonatomic) NSString* _Nonnull trxAddr;
@property (nonatomic) NSString* _Nonnull btlcAddr;
@property (nonatomic) NSString* _Nonnull usdtAddr;
@end

@interface DrawinBeetleLibLibBalance : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
// skipped field LibBalance.BeetleBalance with unsupported type: github.com/TheRealBeetle/beetle-client-lib/config.BeetleBalance

@end

@interface DrawinBeetleLibLibClientTransationLoads : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
// skipped field LibClientTransationLoads.Items with unsupported type: []*github.com/TheRealBeetle/drawin-client-lib.LibClientTranstionItem

@property (nonatomic) int64_t total;
@end

@interface DrawinBeetleLibLibClientTranstionItem : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
// skipped field LibClientTranstionItem.ClientTranstionItem with unsupported type: github.com/TheRealBeetle/beetle-client-lib/db.ClientTranstionItem

@property (nonatomic) NSString* _Nonnull txStr;
- (NSString* _Nonnull)string;
@end

FOUNDATION_EXPORT NSString* _Nonnull const DrawinBeetleLibDatabaseDir;

@interface DrawinBeetleLib : NSObject
+ (DrawinBeetleLibDrawinSlab* _Nullable) beetleInstant;
+ (void) setBeetleInstant:(DrawinBeetleLibDrawinSlab* _Nullable)v;

@end

FOUNDATION_EXPORT BOOL DrawinBeetleLibCreateWallet(NSString* _Nullable auth, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT long DrawinBeetleLibGetCurStationId(void);

FOUNDATION_EXPORT NSString* _Nonnull DrawinBeetleLibGetCurStationName(void);

FOUNDATION_EXPORT NSString* _Nonnull DrawinBeetleLibGetDownLink(void);

FOUNDATION_EXPORT NSString* _Nonnull DrawinBeetleLibGetLicenseExpireDate(void);

FOUNDATION_EXPORT NSString* _Nonnull DrawinBeetleLibGetSationIp(void);

FOUNDATION_EXPORT NSString* _Nonnull DrawinBeetleLibGetStationList(NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT long DrawinBeetleLibGetStreamPort(void);

FOUNDATION_EXPORT NSString* _Nonnull DrawinBeetleLibGetUpLink(void);

FOUNDATION_EXPORT BOOL DrawinBeetleLibGetVpnMode(void);

FOUNDATION_EXPORT BOOL DrawinBeetleLibInitBeetle(NSString* _Nullable basDir, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT void DrawinBeetleLibInitGoLog(NSString* _Nullable sharedPath);

FOUNDATION_EXPORT BOOL DrawinBeetleLibInputPacket(NSData* _Nullable data, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT BOOL DrawinBeetleLibIsBeetleId(NSString* _Nullable id_);

FOUNDATION_EXPORT BOOL DrawinBeetleLibIsCommunicateWalletOpened(void);

FOUNDATION_EXPORT BOOL DrawinBeetleLibIsTokenWalletOpened(void);

FOUNDATION_EXPORT BOOL DrawinBeetleLibIsWalletCreate(void);

FOUNDATION_EXPORT NSString* _Nonnull DrawinBeetleLibLicenseBuy(NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT NSString* _Nonnull DrawinBeetleLibLicenseGetPrice(void);

FOUNDATION_EXPORT NSString* _Nonnull DrawinBeetleLibLicenseGetUserPrice(void);

FOUNDATION_EXPORT BOOL DrawinBeetleLibLicenseIsApplied(void);

FOUNDATION_EXPORT NSString* _Nonnull DrawinBeetleLibLicenseRenew(NSString* _Nullable tx, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT NSString* _Nonnull DrawinBeetleLibLicenseUserPrice(NSString* _Nullable licenseTime, long typ, NSString* _Nullable receiver, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT NSString* _Nonnull DrawinBeetleLibLicenseUserPriceThirdWallet(NSString* _Nullable licenseTime, long typ, NSString* _Nullable receiver, NSString* _Nullable payer, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT void DrawinBeetleLibLoadIps(NSString* _Nullable bypassIPs);

FOUNDATION_EXPORT NSString* _Nonnull DrawinBeetleLibLoadLicenseTransactions(long pageStart, long pageSize, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT NSString* _Nonnull DrawinBeetleLibMarketPriceGet(NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT BOOL DrawinBeetleLibOpenCommunicateWallet(NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT BOOL DrawinBeetleLibOpenTokenWallet(NSString* _Nullable auth, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT BOOL DrawinBeetleLibOpenWallet(NSString* _Nullable auth, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT BOOL DrawinBeetleLibRefreshBalance(NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT BOOL DrawinBeetleLibRefreshLicense(NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT BOOL DrawinBeetleLibRefreshStations(NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT NSString* _Nonnull DrawinBeetleLibRenewAllLicense(NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT BOOL DrawinBeetleLibSaveTransation(NSString* _Nullable tx, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT void DrawinBeetleLibSetCurStation(int64_t id_);

FOUNDATION_EXPORT void DrawinBeetleLibSetVpnMode(BOOL mode);

FOUNDATION_EXPORT BOOL DrawinBeetleLibSetVpnMode2Tun2Pipe(BOOL vpnMode, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT BOOL DrawinBeetleLibStartVpn(NSString* _Nullable ipaddr, NSString* _Nullable ipList, NSString* _Nullable baseDir, int64_t stationId, id<DrawinBeetleLibVpnDelegate> _Nullable vd, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT void DrawinBeetleLibStopVpn(void);

FOUNDATION_EXPORT NSString* _Nonnull DrawinBeetleLibTokenAddress(void);

FOUNDATION_EXPORT NSString* _Nonnull DrawinBeetleLibTokenBalances(void);

FOUNDATION_EXPORT BOOL DrawinBeetleLibTransactionInsert(NSString* _Nullable tx, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT BOOL DrawinBeetleLibUserReg(NSString* _Nullable email, NSString* _Nullable telegram, NSString* _Nullable passwd, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT BOOL DrawinBeetleLibVpnIsStarted(void);

@class DrawinBeetleLibShareDb;

@class DrawinBeetleLibVpnDelegate;

@interface DrawinBeetleLibShareDb : NSObject <goSeqRefInterface, DrawinBeetleLibShareDb> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (void)close;
- (NSString* _Nonnull)get:(NSString* _Nullable)key;
- (NSString* _Nonnull)list:(NSString* _Nullable)start end:(NSString* _Nullable)end;
- (NSString* _Nonnull)listAll;
- (long)put:(NSString* _Nullable)key value:(NSString* _Nullable)value;
@end

@interface DrawinBeetleLibVpnDelegate : NSObject <goSeqRefInterface, DrawinBeetleLibVpnDelegate> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (BOOL)bypass:(int32_t)fd;
- (void)vpnClosed;
- (BOOL)write:(NSData* _Nullable)p0 n:(long* _Nullable)n error:(NSError* _Nullable* _Nullable)error;
@end

#endif
